
package piano;
import sun.audio.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Dell
 */
public class Piano_d extends javax.swing.JFrame {

    /**
     * Creates new form Piano_d
     */
    public Piano_d() {
        initComponents();
        setSize(1215,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCs = new javax.swing.JButton();
        jbCs4 = new javax.swing.JButton();
        jbCs6 = new javax.swing.JButton();
        jbC5 = new javax.swing.JButton();
        jbC6 = new javax.swing.JButton();
        jbC7 = new javax.swing.JButton();
        jbCs3 = new javax.swing.JButton();
        jbC8 = new javax.swing.JButton();
        jbCs5 = new javax.swing.JButton();
        jbC9 = new javax.swing.JButton();
        jbCs7 = new javax.swing.JButton();
        jbCs8 = new javax.swing.JButton();
        jbC11 = new javax.swing.JButton();
        jbC15 = new javax.swing.JButton();
        jbC16 = new javax.swing.JButton();
        jbC17 = new javax.swing.JButton();
        jbC18 = new javax.swing.JButton();
        jbCs9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piano");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        jbCs.setBackground(java.awt.Color.black);
        jbCs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs.setForeground(new java.awt.Color(255, 255, 255));
        jbCs.setText("D#");
        jbCs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCsActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs);
        jbCs.setBounds(240, 150, 71, 180);

        jbCs4.setBackground(java.awt.Color.black);
        jbCs4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs4.setForeground(new java.awt.Color(255, 255, 255));
        jbCs4.setText("C#");
        jbCs4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs4);
        jbCs4.setBounds(120, 150, 69, 180);

        jbCs6.setBackground(java.awt.Color.black);
        jbCs6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs6.setForeground(new java.awt.Color(255, 255, 255));
        jbCs6.setText("Bb");
        jbCs6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs6);
        jbCs6.setBounds(720, 150, 63, 180);

        jbC5.setBackground(java.awt.Color.white);
        jbC5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC5.setText("C");
        jbC5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC5);
        jbC5.setBounds(30, 150, 120, 360);

        jbC6.setBackground(java.awt.Color.white);
        jbC6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC6.setText("D");
        jbC6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC6);
        jbC6.setBounds(150, 150, 120, 360);

        jbC7.setBackground(java.awt.Color.white);
        jbC7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC7.setText("E");
        jbC7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC7);
        jbC7.setBounds(270, 150, 120, 360);

        jbCs3.setBackground(java.awt.Color.black);
        jbCs3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs3.setForeground(new java.awt.Color(255, 255, 255));
        jbCs3.setText("F#");
        jbCs3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs3);
        jbCs3.setBounds(480, 150, 70, 180);

        jbC8.setBackground(java.awt.Color.white);
        jbC8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC8.setText("F");
        jbC8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC8);
        jbC8.setBounds(390, 150, 120, 360);

        jbCs5.setBackground(java.awt.Color.black);
        jbCs5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs5.setForeground(new java.awt.Color(255, 255, 255));
        jbCs5.setText("G#");
        jbCs5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs5);
        jbCs5.setBounds(600, 150, 70, 180);

        jbC9.setBackground(java.awt.Color.white);
        jbC9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC9.setText("G");
        jbC9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC9);
        jbC9.setBounds(510, 150, 120, 360);

        jbCs7.setBackground(java.awt.Color.black);
        jbCs7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs7.setForeground(new java.awt.Color(255, 255, 255));
        jbCs7.setText("C#");
        jbCs7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs7);
        jbCs7.setBounds(950, 150, 69, 180);

        jbCs8.setBackground(java.awt.Color.black);
        jbCs8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs8.setForeground(new java.awt.Color(255, 255, 255));
        jbCs8.setText("D#");
        jbCs8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs8);
        jbCs8.setBounds(1080, 150, 70, 180);

        jbC11.setBackground(java.awt.Color.white);
        jbC11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC11.setText("E");
        jbC11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC11ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC11);
        jbC11.setBounds(1110, 150, 120, 360);

        jbC15.setBackground(java.awt.Color.white);
        jbC15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC15.setText("A");
        jbC15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC15ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC15);
        jbC15.setBounds(630, 150, 120, 360);

        jbC16.setBackground(java.awt.Color.white);
        jbC16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC16.setText("B");
        jbC16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC16ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC16);
        jbC16.setBounds(750, 150, 120, 360);

        jbC17.setBackground(java.awt.Color.white);
        jbC17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC17.setText("C");
        jbC17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC17ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC17);
        jbC17.setBounds(870, 150, 120, 360);

        jbC18.setBackground(java.awt.Color.white);
        jbC18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC18.setText("D");
        jbC18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC18ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC18);
        jbC18.setBounds(990, 150, 120, 360);

        jbCs9.setBackground(java.awt.Color.black);
        jbCs9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCs9.setForeground(new java.awt.Color(255, 255, 255));
        jbCs9.setText("G#");
        jbCs9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCs9);
        jbCs9.setBounds(600, 150, 70, 180);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Virtual Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 40, 500, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, 20, 1240, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCsActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\D_s.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCsActionPerformed

    private void jbC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC5ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\C.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC5ActionPerformed

    private void jbC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC6ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\D.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC6ActionPerformed

    private void jbCs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs4ActionPerformed
         try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\C_s.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs4ActionPerformed

    private void jbC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC7ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\E.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC7ActionPerformed

    private void jbC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC8ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\F.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC8ActionPerformed

    private void jbC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC9ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\G.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC9ActionPerformed

    private void jbCs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs5ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\G_s.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs5ActionPerformed

    private void jbCs6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs6ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\Bb.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs6ActionPerformed

    private void jbC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC11ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\E1.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC11ActionPerformed

    private void jbCs7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs7ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\C_s1.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs7ActionPerformed

    private void jbCs8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs8ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\D_s1.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs8ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_formWindowActivated

    private void jbC15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC15ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\A.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC15ActionPerformed

    private void jbC16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC16ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\B.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC16ActionPerformed

    private void jbC17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC17ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\C1.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC17ActionPerformed

    private void jbC18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC18ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\D1.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbC18ActionPerformed

    private void jbCs9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCs9ActionPerformed

    private void jbCs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs3ActionPerformed
        try {
            InputStream iAudio;
            iAudio =new FileInputStream(new File("D:\\Fci\\My codes\\Java Projects\\Piano\\F_s.wav"));
            AudioStream iMusic =new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Piano_d.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCs3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano_d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano_d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano_d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano_d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano_d().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbC11;
    private javax.swing.JButton jbC15;
    private javax.swing.JButton jbC16;
    private javax.swing.JButton jbC17;
    private javax.swing.JButton jbC18;
    private javax.swing.JButton jbC5;
    private javax.swing.JButton jbC6;
    private javax.swing.JButton jbC7;
    private javax.swing.JButton jbC8;
    private javax.swing.JButton jbC9;
    private javax.swing.JButton jbCs;
    private javax.swing.JButton jbCs3;
    private javax.swing.JButton jbCs4;
    private javax.swing.JButton jbCs5;
    private javax.swing.JButton jbCs6;
    private javax.swing.JButton jbCs7;
    private javax.swing.JButton jbCs8;
    private javax.swing.JButton jbCs9;
    // End of variables declaration//GEN-END:variables
}
